bash: ./run_tests.sh: No such file or directory
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
Traceback (most recent call last):
  File "/app/test_wrapper.py", line 35, in <module>
    code_tester("test", "get_sum")
  File "/app/test_wrapper.py", line 30, in code_tester
    test()
  File "/app/test_wrapper.py", line 22, in test
    output = target_function(test)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/test.py", line 3, in get_sum
    return 7 / 0
           ~~^~~
ZeroDivisionError: division by zero
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
Traceback (most recent call last):
  File "/app/test_wrapper.py", line 35, in <module>
    code_tester("test", "get_sum")
  File "/app/test_wrapper.py", line 30, in code_tester
    test()
  File "/app/test_wrapper.py", line 22, in test
    output = target_function(test)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/test.py", line 3, in get_sum
    return 7 / 0
           ~~^~~
ZeroDivisionError: division by zero
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
Traceback (most recent call last):
  File "/app/test_wrapper.py", line 35, in <module>
    code_tester("test", "get_sum")
  File "/app/test_wrapper.py", line 30, in code_tester
    test()
  File "/app/test_wrapper.py", line 22, in test
    output = target_function(test)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/test.py", line 3, in get_sum
    return 7 / 0
           ~~^~~
ZeroDivisionError: division by zero
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
Traceback (most recent call last):
  File "/app/test_wrapper.py", line 35, in <module>
    code_tester("test", "get_sum")
  File "/app/test_wrapper.py", line 30, in code_tester
    test()
  File "/app/test_wrapper.py", line 22, in test
    output = target_function(test)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/test.py", line 3, in get_sum
    return 7 / 0
           ~~^~~
ZeroDivisionError: division by zero
ERROR: failed to solve: failed to read dockerfile: open Dockerfile: no such file or directory
Traceback (most recent call last):
  File "/app/test_wrapper.py", line 35, in <module>
    code_tester("test", "get_sum")
  File "/app/test_wrapper.py", line 30, in code_tester
    test()
  File "/app/test_wrapper.py", line 22, in test
    output = target_function(test)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/test.py", line 3, in get_sum
    return 7 / 0
           ~~^~~
ZeroDivisionError: division by zero
